import { triggerHandles } from "../handles"
import type { Block } from "../types"

export const schedule: Block = {
  type: "trigger",
  subtype: "schedule",
  name: "Schedule",
  category: "Triggers",
  description: "Run this workflow on a time-based schedule",
  definition: "Runs the workflow at a set time interval.",
  example: "Set to daily at 09:00 to scan for stale PRs every morning.",
  params: [
    {
      key: "scheduleType",
      name: "Run frequency",
      type: "select",
      required: true,
      default: "daily",
      options: [
        { label: "Every X Minutes", value: "minutes" },
        { label: "Hourly", value: "hourly" },
        { label: "Daily", value: "daily" },
        { label: "Weekly", value: "weekly" },
        { label: "Custom (Cron)", value: "custom" },
      ],
    },
    {
      key: "minutesInterval",
      name: "Interval (minutes)",
      type: "number",
      default: 15,
      description: "Run every N minutes",
      condition: { field: "scheduleType", value: "minutes" },
    },
    {
      key: "hourlyMinute",
      name: "Minute",
      type: "number",
      default: 0,
      description: "Minute of the hour (0-59)",
      condition: { field: "scheduleType", value: "hourly" },
    },
    {
      key: "dailyTime",
      name: "Time",
      type: "string",
      default: "09:00",
      description: "Time of day (HH:MM)",
      condition: { field: "scheduleType", value: "daily" },
    },
    {
      key: "weeklyDay",
      name: "Day of week",
      type: "select",
      default: "MON",
      options: [
        { label: "Monday", value: "MON" },
        { label: "Tuesday", value: "TUE" },
        { label: "Wednesday", value: "WED" },
        { label: "Thursday", value: "THU" },
        { label: "Friday", value: "FRI" },
        { label: "Saturday", value: "SAT" },
        { label: "Sunday", value: "SUN" },
      ],
      condition: { field: "scheduleType", value: "weekly" },
    },
    {
      key: "weeklyDayTime",
      name: "Time",
      type: "string",
      default: "09:00",
      description: "Time of day (HH:MM)",
      condition: { field: "scheduleType", value: "weekly" },
    },
    {
      key: "cronExpression",
      name: "Cron expression",
      type: "string",
      description: "Standard 5-field cron (e.g. 0 9 * * MON)",
      condition: { field: "scheduleType", value: "custom" },
    },
    {
      key: "timezone",
      name: "Timezone",
      type: "select",
      default: "UTC",
      options: [
        { label: "UTC", value: "UTC" },
        { label: "US Pacific (UTC-8)", value: "America/Los_Angeles" },
        { label: "US Mountain (UTC-7)", value: "America/Denver" },
        { label: "US Central (UTC-6)", value: "America/Chicago" },
        { label: "US Eastern (UTC-5)", value: "America/New_York" },
        { label: "London (UTC+0)", value: "Europe/London" },
        { label: "Berlin (UTC+1)", value: "Europe/Berlin" },
        { label: "Tokyo (UTC+9)", value: "Asia/Tokyo" },
        { label: "Sydney (UTC+10)", value: "Australia/Sydney" },
      ],
      condition: {
        field: "scheduleType",
        value: ["daily", "weekly", "custom"],
      },
    },
  ],
  handles: triggerHandles,
  requiredContext: [],
  evaluate(_data) {
    return { pass: true, detail: `Triggered: schedule` }
  },
}
